### ISSUE TITLE
Typo in 1.6.1 (HTTPS Authorized Port)

### ISSUE THREAD

**Issue by dzacharo** [cabforum/documents#108]
Change **"443 (http)**" to **"443 (https)"**

**Comment by timfromdigicert** [comment]
This is now in my "minor cleanups" branch:

https://github.com/timfromdigicert/documents/commit/aec4ff775b788f77b87a0270cad5bc293d30a9db

I'll be putting it into a ballot with all the other minor reference and typo changes after next year's spring CABF meeting.
