### ISSUE TITLE
Update incorrect reference in BRs Section 4.1.2

### ISSUE THREAD

**Issue by dzacharo** [cabforum/documents#112]
Instead of referencing 3.3.1 (which is empty), this reference should point to section 4.2.1.

@timfromdigicert this looks like a minor change and could be added on your list of minor cleanups.

**Comment by timfromdigicert** [comment]
https://github.com/timfromdigicert/documents/commit/5a0ba39dda936cc7fafbf7698d2d57941976b6e2?short_path=7f6d14a#diff-7f6d14a20e7f3beb696b45e1bf8196f2
