### ISSUE TITLE
Clarify wording for serial number length

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#116]
The wording for the length of the serial number in chapter 7.1 BRGs seems to be a little bit ambiguous:

> CAs SHALL generate non-sequential Certificate serial numbers greater than zero (0) containing at least 64 bits of output from a CSPRNG.

This could allow the construction of a serial number as following (in pseudo code)

```
serialNumber = CSPRNG.getBitsArray(64).convertTo32BitNumber()
```

which results in a 4 Byte long serial number that can be argued to be BRG compliant. This would be of course against the spirit of this chapter, but not totally clear against the wording.

To be unambiguous here, I would like to propose the following wording:

> CAs SHALL generate non-sequential Certificate serial numbers with a length of at least 8 bytes, greater than zero (0), and containing at least 64 bits of output from a CSPRNG.

**Comment by sleevi** [comment]
Can you please raise this on the list for discussion?

**Comment by sleevi** [comment]
Without signing the IP agreement, I don’t believe it is appropriate to make
suggestions for changes. Perhaps you can consider simply raising the issue
on the questions@ list, without suggesting changes.

I cannot see how the language could possibly support the misreading you
suggest; if a CA acts on such an interpretation, the ecosystem is better
off if they are not a CA.

Regardless, offering suggestions to changes without the IP agreement in
place should result in the issues being summarily closed.

**Comment by dzacharo** [comment]
@RufusJWB you would be able to join as an Interested Party and sign the IPR agreement as an individual that wants to contribute in improving the Requirements. Until then, someone else would have to support your proposals.

**Comment by RufusJWB** [comment]
**Regarding the IPR:** We (Siemens) are working to find a way to sign the IP agreement, but as it is with a company of our size, there are lots of lawyers and lots of IPs and in the consequence a lot of doubt before one can sign a document like this IPR. Now we have found a way how to sign this IPR, but it will take time to implement. Never the less I'm wondering why CA/B Forum has a public repository at GitHub if only members of CA/B Forum shall post here. That feels strange.

**Regarding the wording:** I couldn't agree more with @sleevi , that the interpretation im providing is a clear misreading of the spirit of the BRGs and that "the ecosystem is better off" without a CA having this misreading. But in the discussions about ballot SC12 "Underscores" we have seen, that it makes sense to be as specific as possible, as there are people misunderstanding everything.

**Comment by timfromdigicert** [comment]
I agree that this particular interpretation is too perverse and tortured to be worth addressing.

A value no longer "contains" 64-bits of output after you intentionally truncate it and discard half the bits.

**Comment by sleevi** [comment]
> *Regarding the IPR:* We (Siemens) are working to find a way to sign the
> IP agreement, but as it is with a company of our size, there are lots of
> lawyers and lots of IPs and in the consequence a lot of doubt before one
> can sign a document like this IPR. Now we have found a way how to sign this
> IPR, but it will take time to implement. Never the less I'm wondering why
> CA/B Forum has a public repository at GitHub if only members of CA/B Forum
> shall post here. That feels strange.
>

It is no different than requiring contributor agreements (CLAs). Changes
from folks who can’t/won’t sign the CLA create issues and will be summarily
closed. Bugs filed from folks are welcome, but we have a mail list for bugs
- same as plenty of other open projects.

**Comment by RufusJWB** [comment]
> A value no longer "contains" 64-bits of output after you intentionally truncate it and discard half the bits.

Well, thinking about it, makes me wonder, if not nearly every CA which is creating 64 bit long *positive* serial numbers (as required by the BRGs), is doing something very similar to what you have described: They create a 64 bits number and then throws away half of them, because they are negative and the arithmetic sign is encoded in the [high order bit](https://docs.microsoft.com/en-us/windows/desktop/SecCertEnroll/about-integer). The correct way to achieve the BRGs requirements of positive integers containing 64 bits of random values, would be to create 64 bit positive integers and add eight leading zeros to enforce positive numbers. But I have never heard that any CA software that is doing it like that. So in reality every 64 bit serial number only contains 63 bits output from the CSPRNG.

**Comment by timfromdigicert** [comment]
This isn't true.  The high order bit of an unsigned 64 bit value is not a sign bit.

**Comment by sleevi** [comment]
The high order bit of an ASN.1 INTEGER in DER encoding is a sign but.

Tim, I believe it would be better if we took this issue as filed to the
list. Do you agree?
