### ISSUE TITLE
Possible minor correction for the disclosure of the revocation request procedures

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#119]
BRGs require that the revocation request procedure SHALL be disclosed in the CPS:

Chapter 4.9.3:
> The CA SHALL publicly disclose the instructions through a readily accessible online means and in section 1.5.2 of their **CPS**.

I think it would be reasonable, if a CA could also disclose this information in the CP, when the CP acts as an umbrella for a set of CPSes. In that case every CPS could only hold a 'pointer' to the CP. How do you think about this?

**Comment by wthayer** [comment]
The intent is to make it easier to find this important information. If it was only to be required in the CP OR CPS, I think it would be somewhat harder to find. If anything, perhaps the requirement should have been CP AND CPS.

**Comment by RufusJWB** [comment]
We are trying to have no redundant information in our set of one CP and two CPS. Would you consider it acceptable, if both CPS' state in chapter 1.5.2 "This information is to be found at the same place in the CP."?

**Comment by wthayer** [comment]
No, I don't think that referencing the CP in the CPS meets the requirement as written, nor does it make finding the information easier.

**Comment by RufusJWB** [comment]
Okay. Thank you for the information.
