### ISSUE TITLE
Possible typo in 4.9.1.1

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#120]
Chapter 4.9.1.1. says

> 1. The Subscriber requests in writing that the CA revoke the Certificate;

I'm not very good in English, but I think there is a *s* missing at the end of *revoke*

> 1. The Subscriber requests in writing that the CA revoke**s** the Certificate;

**Comment by timfromdigicert** [comment]
The missing -s in a phrase starting with 'that' indicates that this sentence is an example of the increasingly rare English subjunctive.

If the sentence were not subjunctive, the verb would have been conjugated.

https://en.wikipedia.org/wiki/English_subjunctive

**Comment by RufusJWB** [comment]
@timfromdigicert thank you very much for your explanation. Again what learnt, as we Germans say :-)

**Comment by timfromdigicert** [comment]
Yeah, no problem.  You discovered an obscure, archaic corner of the English language that is rarely even understood by native speakers! :)
