### ISSUE TITLE
Typo in chapter "1.3.4. Relying Parties" when rendered to PDF

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#199]
The start of chapter "1.3.4. Relying Parties" misses a double quote in the PDF file on https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.0.pdf

![image](https://user-images.githubusercontent.com/1633499/86542867-da8d4380-bf19-11ea-9c3e-8e8d73846d59.png)

But it is there in the Markdown rendering at GitHub.

![image](https://user-images.githubusercontent.com/1633499/86542886-fd1f5c80-bf19-11ea-9cad-055fdb44596e.png)

So I believe there is a problem with rendering the PDF file.

**Comment by sleevi** [comment]
Thanks. The current PDF is not generated from the Markdown, but instead maintained by @dzacharo within a Word doc, AIUI.

Dimitris: Sounds like this should be a local fix?

**Comment by dzacharo** [comment]
Fixed. Unfortunately, although I uploaded an updated PDF on WP using the same name, the page still served the old one. There's probably some caching issue that I couldn't find an easy way to overcome, therefore I used a different name and updated the link.

Thanks Rufus.
