### ISSUE TITLE
Wrong reference in chapter 8.4

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#83]
I already reported this issue to the CAB public mailing list but haven't received a feedback so far, therefor I open this issue.

It appear there is a wrong reference in the BRGs, chapter 8.4 “Topics covered by assessment”. This chapter includes the statement 

> The audit MUST be conducted by a Qualified Auditor, as specified in Section 8.3.

This should most probably read

>... specified in Section 8.2

which describes “Identity/qualifications of assessor”. Section 8.3 is empty.

I would propose, this should be changed in one of the upcoming ballots. I would post this directly to the mailing list, but as not being a member, I’m prohibited from posting.

**Comment by timfromdigicert** [comment]
I had been thinking of keeping open a "minor cleanup" branch, and then creating a ballot quarterly or so when we have enough non-controversial editorial cleanups.

This is perfect for that so I think I'll do it now.

**Comment by dzacharo** [comment]
Fixed in https://github.com/cabforum/documents/pull/94/commits/ad94caa1c948d69d03b69d26fb5d948321f243c5
