### ISSUE TITLE
Possible typo in BRG 3.2.2.4.6

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#85]
Chapter 6.2.2.4.6 of the BRGs say

> The presence of the Request Token or Request Value contained in the content of a file where the Request Token or Random Value MUST NOT appear in the request.

I think this is a typo and should be written as

> The presence of the Request Token or ***Random*** Value contained in the content of a file where the Request Token or Random Value MUST NOT appear in the request.

since there is no reference _Request Value_ any more in this chapter.

Could anyone confirm this? Thank you :-)

**Comment by dzacharo** [comment]
I confirm this for **3.2.2.4.6** (not 6.2.2.4.6). It should be updated in an upcoming cleanup ballot. @timfromdigicert keeps track of these typos and small changes.
