### ISSUE TITLE
Remove ETSI TS 102 042 as audit scheme

### ISSUE THREAD

**Issue by RufusJWB** [cabforum/documents#90]
I would like to suggest to remove ETSI TS 102 042 as acceptable audit scheme for two reasons:

1) The most important root store is not accepting ETSI TS 102 042 audits any more: https://github.com/mozilla/pkipolicy/commit/49a07119a1fd5c887d4b506f60e210fad941b26a
2) The ETSI TS 102 042 audit scheme is referencing heavily to the pre-1.3.0-version of the BRGs

==> Both reasons together should be a sufficient reason to remove ETSI TS 102 042 from the BRGs.

**Comment by dzacharo** [comment]
We have identified this problem and tried to address it in the new CA/B Forum Bylaws (https://cabforum.org/pipermail/govreform/2018-February/000373.html) . However, it is a good opportunity to change it in the BRs as well. I will propose a ballot.

**Comment by dzacharo** [comment]
Fixed in https://github.com/cabforum/documents/pull/103/commits/0f2854c53750970b5f207dd462d7909626786244
