### ISSUE TITLE
Minor correction in the "Domain Name Registrar" definition in the BRs

### ISSUE THREAD

**Issue by dzacharo** [cabforum/documents#98]
@timfromdigicert, in the BRs section 1.6.1 in the definition of Domain Name Registrar:

"Domain Name Registrar: A person or entity that registers Domain Names under the auspices of or by agreement with: (i) the Internet Corporation for Assigned Names and Numbers (ICANN), (ii) a national Domain Name authority/registry, or (iii) a Network Information Center (including their affiliates, contractors, delegates, successors, or assigns)."

should be

"Domain Name Registrar: A person or entity that registers Domain Names under the auspices of or by agreement with: (i) the Internet Corporation for Assigned Names and Numbers (ICANN), (ii) a national Domain Name authority/registry, or (iii) a Network Information Center (including their affiliates, contractors, delegates, successors, or **assignees**)."

**Comment by timfromdigicert** [comment]
https://github.com/timfromdigicert/documents/commit/1b2bf190944a7bbd18572ae8f82b0fbc6b39d9cd#diff-7f6d14a20e7f3beb696b45e1bf8196f2
